### PR TITLE
Switch to a more standard way of loading pseudo-steps

### PR DESCRIPTION
**Pull request by abayer**
This is how Declarative works - it avoids needing to do any
whitelisting magic around calling other steps, which seems to have
been the cause for the worst of the whitelistings. More refinement is
definitely still needed, and honestly, I don't know if this works,
because I don't have a k8s env locally. =)

NOTE: `MavenFlowDSLTest#smokeTests` is failing - the transformation of the body isn't working right. I'll revisit that later today or tomorrow morning.

### CODE REVIEW

**Comment by abayer** [comment]
re: the body -> config map logic...I found eventually in Declarative that trying to do closure translation like is being done here was problematic with more complicated bodies. I ended up handling that via AST transformations instead - that avoids any need to worry about whitelisting etc. Will think on it here.

**Comment by abayer** [comment]
I've been able to fairly easily get the arguments other than `StepExtension`s to translate just fine, but gotta figure out what the right way to deal with those cases is.

**Comment by abayer** [comment]
Ok, rewrote the extension translation to work like pre 1.2.x Declarative's `ClosureModelTranslator` (with a `MethodMissingWrapper` interface that we specifically look for in the whitelist to handle differently than any other `methodMissing` invocation case). Tada.

**Comment by abayer** [comment]
Next up is `JXPipelinesWhitelist` - it's too broad currently. For the classes in this plugin (i.e., in `org.jenkinsci.jx.pipelines.*`), we can add `@Whitelisted` to the appropriate methods and constructors, but the `io.fabric8.utils` and `org.apache.maven.model` ones will probably need to be wrapped in static utility methods with `@Whitelisted` annotations on 'em, so that we're not just blanket-whitelisting those whole packages for *all* usage.

**Comment by jstrachan** [comment]
lovely thanks! Lemme merge what you've got so far and we can keep polishing!

**Comment by jstrachan** [comment]
@abayer btw I disabled `MavenFlowDSLTest` for now - as its not a terribly useful test any more. The main integration test, `KubernetesMavenFlowDSLTest` tests the use of the `StepExtensions` and configuration anyways via https://github.com/jstrachan/test-maven-flow-project/blob/agent-label/Jenkinsfile#L9-L24

**Comment by abayer** [comment]
@jstrachan Ok, then I guess I need to get a k8s setup going on my Mac. =)

**Comment by jstrachan** [comment]
@abayer I guess you could trust me or the CI jobs (when they are setup) that the tests work ;)

Setting up [minikube](https://github.com/kubernetes/minikube) on your mac is fairly simple though - and kubernetes is awesome fun ;)

**Comment by abayer** [comment]
Yeah, I think I set up minikube at some time in the past while working on the Declarative agent for the k8s plugin, but I get memory-swamped on my mac so much that I turn off pretty much everything I'm not actively using. =)

**Pull request merged**
